"use client";

import React, { useState } from "react";
import {
  Sparkles,
  Send,
  RefreshCw,
  CheckCircle2,
  FileText,
  Clock,
  MapPin,
  Users,
} from "lucide-react";

export const EmployerPostJob: React.FC = () => {
  const [jobInput, setJobInput] = useState<string>(
    "อยากได้พนักงานเสิร์ฟเพิ่ม 2 คน ทำงานกะเย็น 5 โมงถึง 5 ทุ่ม ร้านอยู่แถวลาดพร้าว เงินเดือนประมาณ 12,000 ไม่ต้องมีประสบการณ์ก็ได้แต่ขยันสำคัญกว่า"
  );
  const [isFormatting, setIsFormatting] = useState<boolean>(false);
  const [isPublished, setIsPublished] = useState<boolean>(false);

  // Structured outputs generated by AI
  const [listingData, setListingData] = useState({
    title: "รับพนักงานเสิร์ฟ 2 อัตรา",
    company: "ร้านอาหารสมศรี",
    location: "ลาดพร้าว",
    shift: "กะเย็น 17:00–23:00",
    salary: "12,000 บาท/เดือน",
    experience: "ไม่จำเป็นต้องมีประสบการณ์",
    headcount: "2 อัตรา",
    description:
      "ร้านอาหารสมศรีกำลังมองหาพนักงานเสิร์ฟกะเย็นเพิ่ม 2 ตำแหน่ง ไม่จำเป็นต้องมีประสบการณ์มาก่อน แต่ต้องการคนขยัน ตรงต่อเวลา และมีใจรักงานบริการ มีอาหารเย็นให้ 1 มื้อ",
  });

  const presetExamples = [
    {
      label: "พนักงานเสิร์ฟกะเย็น",
      text: "อยากได้พนักงานเสิร์ฟเพิ่ม 2 คน ทำงานกะเย็น 5 โมงถึง 5 ทุ่ม ร้านอยู่แถวลาดพร้าว เงินเดือนประมาณ 12,000 ไม่ต้องมีประสบการณ์ก็ได้แต่ขยันสำคัญกว่า",
    },
    {
      label: "ผู้ช่วยครัว / ล้างจาน",
      text: "หาผู้ช่วยในครัว 1 คน ช่วยเตรียมผักล้างจาน ทำงาน 10 โมงเช้าถึง 2 ทุ่ม หยุดวันจันทร์ รายวันวันละ 400 บาท ขอคนสะอาด เรียบร้อย",
    },
    {
      label: "พนักงานแพ็คของคลังสินค้า",
      text: "รับคนช่วยแพ็คพัสดุและจัดสต็อก 3 คน กะเช้า 8:30-17:30 น. อยู่แถวรามอินทรา ค่าแรงวันละ 450 บาท มีเบี้ยขยันเพิ่ม",
    },
  ];

  const handleGenerateListing = () => {
    setIsFormatting(true);
    setIsPublished(false);
    setTimeout(() => {
      setIsFormatting(false);
      // Synthesize output based on input
      if (jobInput.includes("ครัว") || jobInput.includes("ล้างจาน")) {
        setListingData({
          title: "รับผู้ช่วยครัว / ล้างจาน 1 อัตรา",
          company: "ร้านอาหารสมศรี",
          location: "ลาดพร้าว",
          shift: "10:00–20:00 (หยุดวันจันทร์)",
          salary: "400 บาท/วัน",
          experience: "ไม่จำกัดวุฒิ / ยินดีสอนงาน",
          headcount: "1 อัตรา",
          description:
            "ร้านอาหารสมศรีเปิดรับผู้ช่วยครัว 1 อัตรา ทำหน้าที่ช่วยเตรียมวัตถุดิบ ล้างจาน และดูแลความสะอาดพื้นที่ครัว ขอคนขยัน ตรงต่อเวลา และรักษาความสะอาด",
        });
      } else if (jobInput.includes("แพ็ค")) {
        setListingData({
          title: "รับพนักงานแพ็คสินค้า 3 อัตรา",
          company: "ร้านอาหารสมศรี (สาขาจัดส่ง)",
          location: "รามอินทรา - ลาดพร้าว",
          shift: "08:30–17:30 น.",
          salary: "450 บาท/วัน + เบี้ยขยัน",
          experience: "ไม่จำเป็นต้องมีประสบการณ์",
          headcount: "3 อัตรา",
          description:
            "เปิดรับพนักงานช่วยแพ็คอาหารและจัดสต็อกกล่องพัสดุสำหรับเดลิเวอรี 3 ตำแหน่ง งานไม่หนัก มีเบี้ยขยันและโอที",
        });
      } else {
        setListingData({
          title: "รับพนักงานเสิร์ฟ 2 อัตรา",
          company: "ร้านอาหารสมศรี",
          location: "ลาดพร้าว",
          shift: "กะเย็น 17:00–23:00",
          salary: "12,000 บาท/เดือน",
          experience: "ไม่จำเป็นต้องมีประสบการณ์",
          headcount: "2 อัตรา",
          description:
            "ร้านอาหารสมศรีกำลังมองหาพนักงานเสิร์ฟกะเย็นเพิ่ม 2 ตำแหน่ง ไม่จำเป็นต้องมีประสบการณ์มาก่อน แต่ต้องการคนขยัน ตรงต่อเวลา และมีใจรักงานบริการ",
        });
      }
    }, 600);
  };

  const handlePublish = () => {
    setIsPublished(true);
  };

  return (
    <div className="view-enter space-y-6">
      {/* Page Header */}
      <div className="space-y-1">
        <h1 className="text-2xl md:text-3xl font-extrabold text-[var(--ink)] tracking-tight">
          โพสต์งานใหม่
        </h1>
        <p className="text-sm md:text-base text-[var(--ink-soft)]">
          พิมพ์อธิบายงานด้วยภาษาพูดธรรมดา ระบบจะจัดให้เป็นประกาศงานที่อ่านง่าย
        </p>
      </div>

      {/* Main 2-Column Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Natural Language Input (6 cols) */}
        <div className="lg:col-span-6 bg-white border border-[var(--line)] rounded-[var(--radius-lg)] p-6 shadow-xs space-y-4">
          <div>
            <h3 className="text-base font-bold text-[var(--ink)]">
              อธิบายงานที่ต้องการ
            </h3>
            <p className="text-xs text-[var(--ink-soft)] mt-0.5">
              เขียนแบบพูดคุยธรรมดาได้เลย ไม่ต้องเป็นทางการ
            </p>
          </div>

          {/* Preset Prompts for SMEs */}
          <div className="flex flex-wrap gap-2 pt-1">
            <span className="text-[11px] font-bold text-[var(--ink-faint)] self-center">
              ตัวอย่างข้อความ:
            </span>
            {presetExamples.map((ex, idx) => (
              <button
                key={idx}
                type="button"
                onClick={() => setJobInput(ex.text)}
                className="text-[11px] font-semibold bg-[var(--purple-50)] text-[var(--purple-700)] hover:bg-[var(--purple-100)] border border-[var(--purple-200)] rounded-full px-2.5 py-1 transition cursor-pointer"
              >
                {ex.label}
              </button>
            ))}
          </div>

          {/* Text Area */}
          <textarea
            id="job-input"
            rows={7}
            value={jobInput}
            onChange={(e) => setJobInput(e.target.value)}
            placeholder="พิมพ์อธิบายงานที่ต้องการ เช่น ต้องการพนักงานเสิร์ฟ 2 คน กะเย็น 5 โมงถึง 5 ทุ่ม..."
            className="w-full border border-[var(--line)] focus:border-[var(--purple-600)] focus:ring-2 focus:ring-[var(--purple-100)] rounded-2xl p-4 text-xs md:text-sm text-[var(--ink)] outline-none resize-y transition leading-relaxed"
          />

          {/* Action Button */}
          <button
            type="button"
            onClick={handleGenerateListing}
            disabled={isFormatting}
            className="w-full py-3 rounded-full bg-[var(--purple-600)] hover:bg-[var(--purple-700)] active:scale-98 text-white font-bold text-sm shadow-md transition flex items-center justify-center gap-2 cursor-pointer"
          >
            {isFormatting ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin" />
                <span>AI กำลังจัดรูปแบบประกาศ...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                <span>ให้ AI จัดรูปแบบประกาศ (Thai LLM)</span>
              </>
            )}
          </button>
        </div>

        {/* Right Column: AI Formatted Listing Preview (6 cols) */}
        <div className="lg:col-span-6 bg-white border border-[var(--line)] rounded-[var(--radius-lg)] p-6 shadow-xs flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-base font-bold text-[var(--ink)]">
                  ตัวอย่างประกาศงาน
                </h3>
                <p className="text-xs text-[var(--ink-soft)] mt-0.5">
                  พร้อมเผยแพร่ให้คนหางานเห็น
                </p>
              </div>
              <FileText className="w-5 h-5 text-[var(--purple-600)]" />
            </div>

            <hr className="border-t border-[var(--line)] my-4" />

            {/* Listing Preview Box */}
            <div
              id="listing-box"
              className={`border border-[var(--purple-200)] rounded-2xl p-5 bg-[var(--purple-50)] transition-opacity duration-300 ${
                isFormatting ? "opacity-40 ai-shimmer" : "opacity-100"
              }`}
            >
              <div className="inline-flex items-center gap-1.5 bg-[var(--purple-600)] text-white text-[11px] font-bold px-3 py-1 rounded-full shadow-xs mb-3">
                <Sparkles className="w-3.5 h-3.5" />
                <span>จัดรูปแบบโดย AI</span>
              </div>

              <div className="text-lg font-extrabold text-[var(--ink)]">
                {listingData.title}
              </div>
              <div className="text-xs font-semibold text-[var(--purple-700)] mt-0.5 mb-3 flex items-center gap-2">
                <span>{listingData.company}</span>
                <span>·</span>
                <span>{listingData.location}</span>
              </div>

              {/* Tag Row */}
              <div className="flex flex-wrap gap-1.5 mb-3.5">
                <span className="bg-white border border-[var(--line)] text-xs text-[var(--ink)] font-semibold px-2.5 py-1 rounded-lg shadow-2xs">
                  ⏰ {listingData.shift}
                </span>
                <span className="bg-white border border-[var(--line)] text-xs text-emerald-700 font-bold px-2.5 py-1 rounded-lg shadow-2xs">
                  💵 {listingData.salary}
                </span>
                <span className="bg-white border border-[var(--line)] text-xs text-[var(--ink)] font-medium px-2.5 py-1 rounded-lg shadow-2xs">
                  ✨ {listingData.experience}
                </span>
                <span className="bg-white border border-[var(--line)] text-xs text-[var(--purple-700)] font-bold px-2.5 py-1 rounded-lg shadow-2xs">
                  👥 {listingData.headcount}
                </span>
              </div>

              <p className="text-xs text-[var(--ink-soft)] leading-relaxed mb-4">
                {listingData.description}
              </p>

              {/* Publish Button */}
              <button
                type="button"
                onClick={handlePublish}
                disabled={isPublished}
                className={`w-full sm:w-auto px-6 py-2.5 rounded-full font-bold text-xs shadow-xs transition flex items-center justify-center gap-1.5 cursor-pointer ${
                  isPublished
                    ? "bg-emerald-600 text-white"
                    : "bg-[var(--purple-600)] hover:bg-[var(--purple-700)] text-white"
                }`}
              >
                {isPublished ? (
                  <>
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    <span>เผยแพร่แล้ว ✓</span>
                  </>
                ) : (
                  <>
                    <Send className="w-3.5 h-3.5" />
                    <span>เผยแพร่ประกาศ</span>
                  </>
                )}
              </button>
            </div>
          </div>

          {isPublished && (
            <div className="mt-4 p-3.5 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0" />
              <span>
                ประกาศงานของคุณถูกเผยแพร่แล้ว! คนหางานในพื้นที่ 5 กม.
                จะได้รับการแจ้งเตือน
              </span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
